### ISSUE TITLE
CamelCase everything

### ISSUE THREAD

**Issue by nathanevans-wf** [de1ux/prowler#1]
The config options are a mixture of CamelCase and underscore. Use all CamelCase

**Comment by Grant-Nelson** [comment]
@nathanevans-wf I'll try this one

**Comment by sbshah97** [comment]
Hey can I take up this issue if it's still open? :D

**Comment by Grant-Nelson** [comment]
I think ticket was fulfilled by https://github.com/de1ux/prowler/pull/5
@salman-bhai
