### ISSUE TITLE
Create release artifacts

### ISSUE THREAD

**Issue by de1ux** [de1ux/prowler#2]
Need to automatically create a .app that users can easily download.

This should be done with some build automation tool. Doesn't matter which, just needs to be free.

Look at release.sh for the skeleton for generating the .app

**Comment by manuelgu** [comment]
Where would you want to upload the .app file to? Where should users be able to download it?

**Comment by de1ux** [comment]
Ideally in the releases page. Not as a code artifact but a release artifact.
https://github.com/de1ux/prowler/releases/new

**Comment by de1ux** [comment]
Addressing in https://github.com/de1ux/prowler/pull/11
